# Generated by Django 5.1.1 on 2024-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_quotarequest_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotarequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
