# Generated by Django 5.1.1 on 2024-10-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quotarequest_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotarequest',
            name='is_notified',
        ),
    ]
